# Generated by Django 4.1 on 2022-09-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_rename_watchlishtmovie_watchlistmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistmovie',
            name='rating',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='release_date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='review',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='watched',
            field=models.CharField(max_length=500),
        ),
    ]
