# Generated by Django 4.1 on 2022-09-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_watchlistmovie_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistmovie',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='review',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='watchlistmovie',
            name='watched',
            field=models.CharField(max_length=50),
        ),
    ]
